fix TOCTOU issue in gh release create/view

diff --git a/.github/workflows/macos-release.yml b/.github/workflows/macos-release.yml
--- a/.github/workflows/macos-release.yml
+++ b/.github/workflows/macos-release.yml
@@ -9,17 +9,17 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout Code
+      - name: Checkout code
         uses: actions/checkout@v3
       - name: Define release identifier
         id: vars
         run: echo "release=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
-      - name: Check or create release
+      - name: Create release if it does not already exist
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          if ! gh release view ${{ steps.vars.outputs.release }}; then
-            gh release create --title ${{ steps.vars.outputs.release }} ${{ steps.vars.outputs.release }}
+          if ! gh release create --title ${{ steps.vars.outputs.release }} ${{ steps.vars.outputs.release }}; then
+            echo "gh release create failed: assume release already exists"
           fi
         shell: bash
       - name: Upload macOS version
